name: Publish package to GitHub Packages

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew --daemon build
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: ${{ github.workspace }}
      - name: Persist failure report
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: failure-report
          path: build/reports/
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: ${{ github.workspace }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish package to registry
        run: ./gradlew --daemon publish
        env:
          MAVEN_REGISTRY_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          MAVEN_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
